engines:
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - ".gitignore"
    - "Documentation/**"
    - "Licenses/**"
    - "Script_Helpers/**"
    - "Paranoid_Pipes.sh"
    - "ReadMe.md"
exclude_paths:
  - ".git/**"
  - "**.gpg"
  - "**.log"
  - "**.pipe"
  - "Bulk_**/**"
  - "bulk_**/**"
  - "Licenses/GNU_AGPLv3_Code.md"
  - "Licenses/GNU_FDLv1.3_Documentation.md"
