## Required for apt-get commands?
sudo: required
## Settings for git
git:
 depth: 3
 branch: master
## Operating systems to test on
os:
 - linux
## Settings for language that travis-ci.org will test with
language:
 - bash
## Custom setup prior to testing project, install dependencies & configure
before_install:
 - chmod +x .travis-ci/before_install_depends.sh
 - .travis-ci/before_install_depends.sh
 - chmod +x .travis-ci/before_install_gen_key.sh
 - .travis-ci/before_install_gen_key.sh
 - chmod +x .travis-ci/before_install_test_key.sh
 - .travis-ci/before_install_test_key.sh
## Steps for successful install once dependencies are met.
install:
 - chmod +x .travis-ci/install.sh
 - .travis-ci/install.sh
## Steps to complete prior to running further tests.
#before_script:
# - chmod +x 
# - .travis-ci/
## Run tests for travis-ci.org to report on
#script:
# - chmod +x .travis-ci/script_encrypt.sh
# - .travis-ci/script_encrypt.sh
## Dissabled decryption checks until local tests are complete.
# - chmod +x .travis-ci/script_decrypt.sh
# - .travis-ci/script_decrypt.sh
## Setps to complete after success or falure
#after_success:
#after_failure:
## Steps to run for deployment of build if any
#before_deploy:
#deploy:
#after_deploy:
## Steps to run when script and deployment is finished; cleanup?
#after_script:
## Note above tricks for chmoding the scripts prior to execution where found
##  at: http://stackoverflow.com/a/33820642/2632107
