## Referance defaults from documentation hosted at: https://jekyllrb.com/docs/configuration/

### Where things are
layouts_dir: _layouts

### Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - github-pages
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Bulk_*
  - .jekyll_configs/.htaccess
include:
  - _pages
keep_files:
  - .git
  - .svn
encoding: "utf-8"
marddown_ext: "markdown,mkdown,mkdn,mkd.md"

## GitHub related settings
baseurl: /Perinoid_Pipes
#repositiory: https://github.com/S0AndS0/Perinoid_Pipes
repositiory: S0AndS0/Perinoid_Pipes

defaults:
  values:
    theme: jekyll-theme-hacker
    layout: "default"
    author: "S0AndS0"
    show-downloads: false
    title: Perinoid Pipes
    email: strangerthanbland@gmail.com
    category: "Scripting"
    description: Where named pipes, GnuPG public key encryption, and other tools are combined.
    twitter_username: S0AndS0
    github_username: S0AndS0
#   google_analytics:

liquid:
  error_mode: strict
